const data = [
  {
    score: 9.04,
    scored_by: 151147,
    rank: 9,
    popularity: 705,
    members: 294168,
    favorites: 2881,
    synopsis:
      "While Gintoki Sakata was away, the Yorozuya found themselves a new leader: Kintoki, Gintoki's golden-haired doppelganger. In order to regain his former position, Gintoki will need the help of those around him, a troubling feat when no one can remember him! Between Kintoki and Gintoki, who will claim the throne as the main character? In addition, Yorozuya make a trip back down to red-light district of Yoshiwara to aid an elderly courtesan in her search for her long-lost lover. Although the district is no longer in chains beneath the earth's surface, the trio soon learn of the tragic backstories of Yoshiwara's inhabitants that still haunt them. With flashback after flashback, this quest has Yorozuya witnessing everlasting love and protecting it as best they can with their hearts and souls. Gintama': Enchousen includes moments of action-packed intensity along with their usual lighthearted, slapstick humor for Gintoki and his friends. [Written by MAL Rewrite]",
    background:
      "This is a third season of Gintama. In the episode continuity corresponds to episodes 253-265 of Gintama.",
    season: "fall",
    year: 2012,
    broadcast: {
      day: "Thursdays",
      time: "18:00",
      timezone: "Asia/Tokyo",
      string: "Thursdays at 18:00 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object], [Object]],
    licensors: [],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["action", "fantasy"],
  },
  {
    mal_id: 11061,
    url: "https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "D9iTQRB4XRk",
      url: "https://www.youtube.com/watch?v=D9iTQRB4XRk",
      embed_url:
        "https://www.youtube.com/embed/D9iTQRB4XRk?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "Hunter x Hunter (2011)",
    title_english: "Hunter x Hunter",
    title_japanese: "HUNTER×HUNTER（ハンター×ハンター）",
    title_synonyms: ["HxH (2011)"],
    type: "TV",
    source: "Manga",
    episodes: 148,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2011-10-02T00:00:00+00:00",
      to: "2014-09-24T00:00:00+00:00",
      prop: [Object],
      string: "Oct 2, 2011 to Sep 24, 2014",
    },
    duration: "23 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 9.04,
    scored_by: 1558456,
    rank: 10,
    popularity: 10,
    members: 2495659,
    favorites: 190751,
    synopsis:
      "Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before becoming a Hunter, one must pass the Hunter Examination—a high-risk selection process in which most applicants end up handicapped or worse, deceased. Ambitious participants who challenge the notorious exam carry their own reason. What drives 12-year-old Gon Freecss is finding Ging, his father and a Hunter himself. Believing that he will meet his father by becoming a Hunter, Gon takes the first step to walk the same path. During the Hunter Examination, Gon befriends the medical student Leorio Paladiknight,",
    background: null,
    season: "fall",
    year: 2011,
    broadcast: {
      day: "Sundays",
      time: "10:55",
      timezone: "Asia/Tokyo",
      string: "Sundays at 10:55 (JST)",
    },
    producers: [[Object], [Object], [Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [],
    demographics: [[Object]],
    stringGenres: ["drama"],
  },
  {
    mal_id: 820,
    url: "https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "Ou37P25tjJY",
      url: "https://www.youtube.com/watch?v=Ou37P25tjJY",
      embed_url:
        "https://www.youtube.com/embed/Ou37P25tjJY?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "Ginga Eiyuu Densetsu",
    title_english: "Legend of the Galactic Heroes",
    title_japanese: "銀河英雄伝説",
    title_synonyms: [
      "LoGH",
      "LotGH",
      "Gin'eiden",
      "GinEiDen",
      "Heldensagen Vom Kosmosinsel",
    ],
    type: "OVA",
    source: "Novel",
    episodes: 110,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "1988-01-08T00:00:00+00:00",
      to: "1997-03-17T00:00:00+00:00",
      prop: [Object],
      string: "Jan 8, 1988 to Mar 17, 1997",
    },
    duration: "26 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 9.03,
    scored_by: 72590,
    rank: 11,
    popularity: 712,
    members: 291272,
    favorites: 15088,
    synopsis:
      "The 150-year-long stalemate between the two interstellar superpowers, the Galactic Empire and the Free Planets Alliance, comes to an end when a new generation of leaders arises: the idealistic military genius Reinhard von Lohengramm, and the FPA's reserved historian, Yang Wenli. While Reinhard climbs the ranks of the Empire with the aid of his childhood friend, Siegfried Kircheis, he must fight not only the war, but also the remnants of the crumbling Goldenbaum Dynasty in order to free his sister from the Kaiser and unify humanity under one genuine ruler. Meanwhile, on the other side of the galaxy, Yang—a strong supporter of democratic ideals—has to stand firm",
    background:
      "Legend of the Galactic Heroes was adapted from a series of ten novels, published 1982–87, by Yoshiki Tanaka. The novels won the Seiun Award for the best long-form Japanese science fiction in 1988. At the start of its production the anime was distributed through a subscription system in which episodes were mailed to existing fans of the novels. It was made in four separate tranches over nearly a decade, with the production of side-stories continuing for several further years. The main series",
    season: null,
    year: null,
    broadcast: { day: null, time: null, timezone: null, string: null },
    producers: [[Object], [Object], [Object], [Object], [Object]],
    licensors: [[Object]],
    studios: [[Object], [Object]],
    genres: [[Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object]],
    demographics: [],
    stringGenres: ["sci-fi"],
  },
  {
    mal_id: 42938,
    url: "https://myanimelist.net/anime/42938/Fruits_Basket__The_Final",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "Ip8Btv2t_6c",
      url: "https://www.youtube.com/watch?v=Ip8Btv2t_6c",
      embed_url:
        "https://www.youtube.com/embed/Ip8Btv2t_6c?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "Fruits Basket: The Final",
    title_english: "Fruits Basket: The Final Season",
    title_japanese: "フルーツバスケット The Final",
    title_synonyms: [
      "Fruits Basket 3rd Season",
      "Fruits Basket (2019) 3rd Season",
      "Furuba",
    ],
    type: "TV",
    source: "Manga",
    episodes: 13,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2021-04-06T00:00:00+00:00",
      to: "2021-06-29T00:00:00+00:00",
      prop: [Object],
      string: "Apr 6, 2021 to Jun 29, 2021",
    },
    duration: "23 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 9.02,
    scored_by: 187432,
    rank: 12,
    popularity: 508,
    members: 383270,
    favorites: 17562,
    synopsis:
      "Hundreds of years ago, the Chinese Zodiac spirits and their god swore to stay together eternally. United by this promise, the possessed members of the Souma family shall always return to each other under any circumstances. Yet, when these bonds shackle them from freedom, it becomes an undesirable burden—a curse. As head of the clan, Akito is convinced that he shares a special connection with the other Soumas. While he desperately clings to this fantasy, the rest of the family remains isolated",
    background: null,
    season: "spring",
    year: 2021,
    broadcast: {
      day: "Tuesdays",
      time: "01:30",
      timezone: "Asia/Tokyo",
      string: "Tuesdays at 01:30 (JST)",
    },
    producers: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object]],
    demographics: [[Object]],
    stringGenres: ["action", "comedy"],
  },
  {
    mal_id: 34096,
    url: "https://myanimelist.net/anime/34096/Gintama",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "LOdAAEJiebM",
      url: "https://www.youtube.com/watch?v=LOdAAEJiebM",
      embed_url:
        "https://www.youtube.com/embed/LOdAAEJiebM?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object]],
    title: "Gintama.",
    title_english: "Gintama Season 5",
    title_japanese: "銀魂。",
    title_synonyms: ["Gintama (2017)"],
    type: "TV",
    source: "Manga",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2017-01-09T00:00:00+00:00",
      to: "2017-03-27T00:00:00+00:00",
      prop: [Object],
      string: "Jan 9, 2017 to Mar 27, 2017",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.99,
    scored_by: 131527,
    rank: 13,
    popularity: 744,
    members: 281148,
    favorites: 2566,
    synopsis:
      "After joining the resistance against the bakufu, Gintoki and the gang are in hiding, along with Katsura and his Joui rebels. The Yorozuya is soon approached by Nobume Imai and two members of the Kiheitai, who explain that the Harusame pirates have turned against 7th Division Captain Kamui and their former ally Takasugi. The Kiheitai present Gintoki with a job: find Takasugi, who has been missing since his ship was ambushed in a Harusame raid. Nobume also makes a stunning revelation regarding the Tendoushuu, a secret organization pulling the strings of numerous factions, and their leader Utsuro, the shadowy figure with an uncanny resemblance to Gintoki's former",
    season: "winter",
    year: 2017,
    broadcast: {
      day: "Mondays",
      time: "01:35",
      timezone: "Asia/Tokyo",
      string: "Mondays at 01:35 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object]],
    licensors: [],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["romance"],
  },
  {
    mal_id: 35180,
    url: "https://myanimelist.net/anime/35180/3-gatsu_no_Lion_2nd_Season",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "OfSaJb5OOPA",
      url: "https://www.youtube.com/watch?v=OfSaJb5OOPA",
      embed_url:
        "https://www.youtube.com/embed/OfSaJb5OOPA?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "3-gatsu no Lion 2nd Season",
    title_english: "March Comes In Like A Lion 2nd Season",
    title_japanese: "3月のライオン 第2シリーズ",
    title_synonyms: ["Sangatsu no Lion Second Season"],
    type: "TV",
    source: "Manga",
    episodes: 22,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2017-10-14T00:00:00+00:00",
      to: "2018-03-31T00:00:00+00:00",
      prop: [Object],
      string: "Oct 14, 2017 to Mar 31, 2018",
    },
    duration: "25 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.95,
    scored_by: 182972,
    rank: 14,
    popularity: 537,
    members: 365549,
    favorites: 14513,
    synopsis:
      "Now in his second year of high school, Rei Kiriyama continues pushing through his struggles in the professional shogi world as well as his personal life. Surrounded by vibrant personalities at the shogi hall, the school club, and in the local community, his solitary shell slowly begins to crack. Among them are the three Kawamoto sisters—Akari, Hinata, and Momo—who forge an affectionate and familial bond with Rei. Through these ties, he realizes that everyone is burdened by their own emotional",
    background: null,
    season: "fall",
    year: 2017,
    broadcast: {
      day: "Saturdays",
      time: "23:00",
      timezone: "Asia/Tokyo",
      string: "Saturdays at 23:00 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object], [Object], [Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["test"],
  },
  {
    mal_id: 28851,
    url: "https://myanimelist.net/anime/28851/Koe_no_Katachi",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "XBNWo25izJ8",
      url: "https://www.youtube.com/watch?v=XBNWo25izJ8",
      embed_url:
        "https://www.youtube.com/embed/XBNWo25izJ8?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "Koe no Katachi",
    title_english: "A Silent Voice",
    title_japanese: "聲の形",
    title_synonyms: ["The Shape of Voice"],
    type: "Movie",
    source: "Manga",
    episodes: 1,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2016-09-17T00:00:00+00:00",
      to: null,
      prop: [Object],
      string: "Sep 17, 2016",
    },
    duration: "2 hr 10 min",
    rating: "PG-13 - Teens 13 or older",
    score: 8.95,
    scored_by: 1439704,
    rank: 15,
    popularity: 18,
    members: 2060685,
    favorites: 79498,
    synopsis:
      "As a wild youth, elementary school student Shouya Ishida sought to beat boredom in the cruelest ways. When the deaf Shouko Nishimiya transfers into his class, Shouya and the rest of his class thoughtlessly bully her for fun. However, when her mother notifies the school, he is singled out and blamed for everything done to her. With Shouko transferring out of the school, Shouya is left at the mercy of his classmates. He is heartlessly ostracized all throughout elementary and middle school, while teachers turn a blind eye. Now in his third year of high school, Shouya is still plagued by his wrongdoings as a young boy. Sincerely regretting his past actions, he sets out on a journey of redemption: to meet Shouko once more and make amends. Koe no Katachi tells the heartwarming tale of Shouya's reunion with Shouko and his honest attempts to redeem himself, all while being continually haunted by the shadows of his past. [Written by MAL Rewrite]",
    background:
      "Winner of the Excellence Award at the 20th Japan Media Arts Festival.",
    season: null,
    year: null,
    broadcast: { day: null, time: null, timezone: null, string: null },
    producers: [[Object], [Object], [Object], [Object], [Object]],
    licensors: [[Object], [Object]],
    studios: [[Object]],
    genres: [[Object], [Object]],
    explicit_genres: [],
    themes: [[Object]],
    demographics: [[Object]],
    stringGenres: ["action"],
  },
  {
    mal_id: 4181,
    url: "https://myanimelist.net/anime/4181/Clannad__After_Story",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "WiTwXIAcm5Q",
      url: "https://www.youtube.com/watch?v=WiTwXIAcm5Q",
      embed_url:
        "https://www.youtube.com/embed/WiTwXIAcm5Q?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object], [Object]],
    title: "Clannad: After Story",
    title_english: "Clannad: After Story",
    title_japanese: "CLANNAD〜AFTER STORY〜 クラナド アフターストーリー",
    title_synonyms: [],
    type: "TV",
    source: "Visual novel",
    episodes: 24,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2008-10-03T00:00:00+00:00",
      to: "2009-03-27T00:00:00+00:00",
      prop: [Object],
      string: "Oct 3, 2008 to Mar 27, 2009",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.94,
    scored_by: 622244,
    rank: 16,
    popularity: 107,
    members: 1109332,
    favorites: 67558,
    synopsis:
      "Clannad: After Story, the sequel to the critically acclaimed slice-of-life series Clannad, begins after Tomoya Okazaki and Nagisa Furukawa graduate from high school. Together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic",
    background: null,
    season: "fall",
    year: 2008,
    broadcast: {
      day: "Fridays",
      time: "01:59",
      timezone: "Asia/Tokyo",
      string: "Fridays at 01:59 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [],
    demographics: [],
    stringGenres: ["action", "drama"],
  },
  {
    mal_id: 918,
    url: "https://myanimelist.net/anime/918/Gintama",
    images: { jpg: [Object], webp: [Object] },
    trailer: { youtube_id: null, url: null, embed_url: null, images: [Object] },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object], [Object]],
    title: "Gintama",
    title_english: "Gintama",
    title_japanese: "銀魂",
    title_synonyms: ["Gin Tama", "Silver Soul", "Yorinuki Gintama-san"],
    type: "TV",
    source: "Manga",
    episodes: 201,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2006-04-04T00:00:00+00:00",
      to: "2010-03-25T00:00:00+00:00",
      prop: [Object],
      string: "Apr 4, 2006 to Mar 25, 2010",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.94,
    scored_by: 367963,
    rank: 17,
    popularity: 137,
    members: 974154,
    favorites: 56007,
    synopsis: `Edo is a city that was home to the vigor and ambition of samurai across the country. However, following feudal Japan's surrender to powerful aliens known as the "Amanto," those aspirations now seem unachievable. With the once-influential shogunate rebuilt as a puppet government, a new law is passed that promptly prohibits all swords in public. Enter Gintoki Sakata, an eccentric silver-haired man who always carries around a wooden sword and maintains his stature as a samurai despite the ban. As the founder of Yorozuya, a small business for odd jobs, Gintoki often embarks on endeavors to help other people—though usually in rather strange and unforeseen ways. Assisted by Shinpachi Shimura, a boy with glasses supposedly learning the way of the samurai; Kagura, a tomboyish girl with superhuman strength and an endless appetite; and Sadaharu, their giant pet dog who loves biting on people's heads, the Yorozuya encounter anything from alien royalty to scuffles with local gangs in the ever-changing world 
of Edo. [Written by MAL Rewrite]`,
    background:
      "Several games based on Gintama have been released on a variety of platforms, such as the PlayStation 2, PlayStation Portable, and Nintendo DS. Characters",
    season: "spring",
    year: 2006,
    broadcast: {
      day: "Thursdays",
      time: "18:00",
      timezone: "Asia/Tokyo",
      string: "Thursdays at 18:00 (JST)",
    },
    producers: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    licensors: [[Object], [Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["action"],
  },
  {
    mal_id: 37987,
    url: "https://myanimelist.net/anime/37987/Violet_Evergarden_Movie",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "NSIzsFOfd8M",
      url: "https://www.youtube.com/watch?v=NSIzsFOfd8M",
      embed_url:
        "https://www.youtube.com/embed/NSIzsFOfd8M?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object], [Object]],
    title: "Violet Evergarden Movie",
    title_english: "Violet Evergarden the Movie",
    title_japanese: "劇場版 ヴァイオレット・エヴァーガーデン",
    title_synonyms: ["Gekijouban Violet Evergarden"],
    type: "Movie",
    source: "Light novel",
    episodes: 1,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2020-09-18T00:00:00+00:00",
      to: null,
      prop: [Object],
      string: "Sep 18, 2020",
    },
    duration: "2 hr 20 min",
    rating: "PG-13 - Teens 13 or older",
    score: 8.93,
    scored_by: 205091,
    rank: 18,
    popularity: 392,
    members: 485340,
    favorites: 7441,
    synopsis:
      'Several years have passed since the end of The Great War. As the radio tower in Leidenschaftlich continues to be built, telephones will soon become more relevant, leading to a decline in demand for "Auto Memory Dolls." Even so, Violet Evergarden continues to rise in fame after her constant success with writing letters. However, sometimes the one thing you long for is the one thing that does not appear. Violet Evergarden Movie follows Violet as she continues to comprehend the concept of emotion and the meaning of love. At the same time, she pursues a glimmer of hope that the man who once told her, "I love you," may still be alive even after the many years that have passed. [Written by MAL Rewrite]',
    background:
      "Winner of the Excellence Award at the 24th Japan Media Arts Festival. It also won the Animation of the Year award in the Film category at the Tokyo Anime",
    season: null,
    year: null,
    broadcast: { day: null, time: null, timezone: null, string: null },
    producers: [[Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [],
    demographics: [],
    stringGenres: ["comedy"],
  },
  {
    mal_id: 15335,
    url: "https://myanimelist.net/anime/15335/Gintama_Movie_2__Kanketsu-hen_-_Yorozuya_yo_Eien_Nare",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "UhJM5rVqaF8",
      url: "https://www.youtube.com/watch?v=UhJM5rVqaF8",
      embed_url:
        "https://www.youtube.com/embed/UhJM5rVqaF8?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object]],
    title: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
    title_english: null,
    title_japanese: "劇場版 銀魂 完結篇 万事屋よ永遠なれ",
    title_synonyms: [
      "Gintama: The Final Chapter - Be Forever Yorozuya",
      "Gintama Movie 2",
    ],
    type: "Movie",
    source: "Manga",
    episodes: 1,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2013-07-06T00:00:00+00:00",
      to: null,
      prop: [Object],
      string: "Jul 6, 2013",
    },
    duration: "1 hr 50 min",
    rating: "PG-13 - Teens 13 or older",
    score: 8.92,
    scored_by: 124909,
    rank: 19,
    popularity: 943,
    members: 218475,
    favorites: 2037,
    synopsis: `When Gintoki apprehends a movie pirate at a premiere, he checks the camera's footage and finds himself transported to a bleak, post-apocalyptic version of Edo, where a mysterious epidemic called the "White Plague" has ravished the world's population. It turns out that the movie pirate wasn't a pirate after all—it was an android time machine, and Gintoki has been hurtled five years into the future! Shinpachi and Kagura, his Yorozuya cohorts, have had a falling out and are now battle-hardened solo vigilantes and he himself has been missing for years, disappearing without a trace after scribbling a strange message in his journal. Setting out in the disguise given 
to him by the android time machine, Gintoki haphazardly reunites the Yorozuya team to investigate the White Plague, and soon discovers that the key to saving the future lies in the darkness of his own past. Determined to confront a powerful foe, he makes an important discovery—with a ragtag band of friends and allies at his side, he doesn't have to fight alone. [Written by MAL Rewrite]`,
    background: null,
    season: null,
    year: null,
    broadcast: { day: null, time: null, timezone: null, string: null },
    producers: [[Object], [Object], [Object], [Object], [Object], [Object]],
    licensors: [],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["sci-fi"],
  },
  {
    mal_id: 44511,
    url: "https://myanimelist.net/anime/44511/Chainsaw_Man",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "q15CRdE5Bv0",
      url: "https://www.youtube.com/watch?v=q15CRdE5Bv0",
      embed_url:
        "https://www.youtube.com/embed/q15CRdE5Bv0?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object]],
    title: "Chainsaw Man",
    title_english: "Chainsaw Man",
    title_japanese: "チェンソーマン",
    title_synonyms: [],
    type: "TV",
    source: "Manga",
    episodes: 12,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "2022-10-12T00:00:00+00:00",
      to: null,
      prop: [Object],
      string: "Oct 12, 2022 to ?",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.91,
    scored_by: 119799,
    rank: 20,
    popularity: 200,
    members: 771772,
    favorites: 22826,
    synopsis:
      "Denji is robbed of a normal teenage life, left with nothing but his deadbeat father's overwhelming debt. His only companion is his pet, the chainsaw devil Pochita, with whom he slays devils for money that inevitably ends up in the yakuza's pockets. All Denji can do is dream of a good, simple life: one with delicious food and'",
    season: "fall",
    year: 2022,
    broadcast: {
      day: "Wednesdays",
      time: "00:00",
      timezone: "Asia/Tokyo",
      string: "Wednesdays at 00:00 (JST)",
    },
    producers: [],
    licensors: [],
    studios: [[Object]],
    genres: [[Object], [Object]],
    explicit_genres: [],
    themes: [[Object]],
    demographics: [[Object]],
    stringGenres: ["fantasy"],
  },
  {
    mal_id: 2904,
    url: "https://myanimelist.net/anime/2904/Code_Geass__Hangyaku_no_Lelouch_R2",
    images: { jpg: [Object], webp: [Object] },
    trailer: { youtube_id: null, url: null, embed_url: null, images: [Object] },
    approved: true,
    titles: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    title: "Code Geass: Hangyaku no Lelouch R2",
    title_english: "Code Geass: Lelouch of the Rebellion R2",
    title_japanese: "コードギアス 反逆のルルーシュ 続編",
    title_synonyms: [
      "Code Geass: Hangyaku no Lelouch 2nd Season",
      "Code Geass: Hangyaku no Lelouch Second Season",
    ],
    type: "TV",
    source: "Original",
    episodes: 25,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2008-04-06T00:00:00+00:00",
      to: "2008-09-28T00:00:00+00:00",
      prop: [Object],
      string: "Apr 6, 2008 to Sep 28, 2008",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.91,
    scored_by: 1102563,
    rank: 21,
    popularity: 46,
    members: 1624369,
    favorites: 72587,
    synopsis:
      "One year has passed since the Black Rebellion, a failed uprising against the Holy Britannian Empire led by the masked vigilante Zero, who is now missing. At a loss without their revolutionary leader, Area 11's resistance group—the Black Knights—find themselves too powerless to combat the brutality inflicted upon the Elevens by Britannia, which has increased significantly in order to crush any hope of a future revolt. Lelouch Lamperouge, having lost all memory of his double life, is living peacefully alongside his friends as a high school student at Ashford Academy. His former partner C.C., unable to accept this turn of events, takes it upon herself to remind him of his past purpose, hoping that the mastermind Zero will rise once again to finish what he started, in this thrilling conclusion to the series. [Written by MAL Rewrite]",
    background: `Code Geass: Hangyaku no Lelouch R2 is an original anime series by Sunrise animation studio with original character designs by the all-female Japanese manga artist group CLAMP. Manga and light novels based off the show have been published by Kadokawa Shoten. The show has sold millions of DVDs and Blu-ray volumes and is extremely popular in both Japan and North America. The show is known for its multi-genre appeal and for its diverse cast of characters who face many moral dilemmas over the course of the series. The series won: "The Best TV Animation" award at the thirteenth Animation Kobe event in 2008, and "The Most Popular Anime" award at the Animage 's 30th 
Annual Anime Grand Prix.`,
    season: "spring",
    year: 2008,
    broadcast: {
      day: "Sundays",
      time: "17:00",
      timezone: "Asia/Tokyo",
      string: "Sundays at 17:00 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object], [Object]],
    licensors: [[Object], [Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object]],
    demographics: [],
    stringGenres: ["action", "drama"],
  },
  {
    mal_id: 35247,
    url: "https://myanimelist.net/anime/35247/Owarimonogatari_2nd_Season",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "7WdyIcDlK2o",
      url: "https://www.youtube.com/watch?v=7WdyIcDlK2o",
      embed_url:
        "https://www.youtube.com/embed/7WdyIcDlK2o?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object]],
    title: "Owarimonogatari 2nd Season",
    title_english: "Owarimonogatari Second Season",
    title_japanese: "終物語",
    title_synonyms: ["End Story 2nd Season"],
    type: "TV",
    source: "Light novel",
    episodes: 7,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2017-08-12T00:00:00+00:00",
      to: "2017-08-13T00:00:00+00:00",
      prop: [Object],
      string: "Aug 12, 2017 to Aug 13, 2017",
    },
    duration: "22 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.89,
    scored_by: 175382,
    rank: 22,
    popularity: 545,
    members: 362521,
    favorites: 8242,
    synopsis:
      "Following an encounter with oddity specialist Izuko Gaen, third-year high school student Koyomi Araragi wakes up in a strange, deserted void only to be greeted by a joyfully familiar face in an alarmingly unfamiliar place. Araragi, with the help of his girlfriend Hitagi Senjougahara, maneuvers through the webs of his past and the perplexities of the present in search of answers. However, fate once again delivers him to the eccentric transfer student Ougi Oshino, who brings forth an unexpected",
    background:
      "Owarimonogatari 2nd Season adapts the fifth volume of NisiOisiN's Monogatari Series: Final Season.",
    season: "summer",
    year: 2017,
    broadcast: {
      day: null,
      time: null,
      timezone: null,
      string: "Not scheduled once per week",
    },
    producers: [[Object], [Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object]],
    demographics: [],
    stringGenres: ["drama"],
  },
  {
    mal_id: 37491,
    url: "https://myanimelist.net/anime/37491/Gintama__Shirogane_no_Tamashii-hen_-_Kouhan-sen",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "E2rzD37MCSg",
      url: "https://www.youtube.com/watch?v=E2rzD37MCSg",
      embed_url:
        "https://www.youtube.com/embed/E2rzD37MCSg?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object]],
    title: "Gintama.: Shirogane no Tamashii-hen - Kouhan-sen",
    title_english: "Gintama.: Silver Soul Arc - Second Half War",
    title_japanese: "銀魂. 銀ノ魂篇 後半戦",
    title_synonyms: ["Gintama.: Silver Soul Arc 2"],
    type: "TV",
    source: "Manga",
    episodes: 14,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2018-07-09T00:00:00+00:00",
      to: "2018-10-08T00:00:00+00:00",
      prop: [Object],
      string: "Jul 9, 2018 to Oct 8, 2018",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.88,
    scored_by: 84074,
    rank: 23,
    popularity: 1185,
    members: 173368,
    favorites: 986,
    synopsis:
      "Following the temporary retreat of the Altana Liberation Army from the Kabuki District, the state of the war has seemingly improved. However, as the Oniwaban, Shinsengumi, and residents of the district combat the army's remnants, Edo's greatest inventor Gengai Hiraga is abducted. Responsible for causing the enemy's withdrawal by rendering their weapons useless, Gengai's nanomachine virus is now at risk of being shut down. Meanwhile, a laser capable of obliterating a planet is activated in Earth's orbit on the Liberation Army's mother ship. Another battle ensues when Shinsuke Takasugi and the rest of the Kiheitai arrive on the vessel to stop the weapon from firing. Forced to fight a war on two fronts, the Yorozuya and their allies must prevail on both sides to save Edo and the rest of the world. [Written by MAL Rewrite]",
    background:
      "Gintama.: Shirogane no Tamashii-hen - Kouhan-sen is the second season of Gintama's final arc and the eighth season of Gintama's continuity. In the episode continuity, this corresponds to episodes 354-367 of Gintama. The anime was released on Blu-ray and DVD from October 24, 2018 to February 27, 2019 in Japan.",
    season: "summer",
    year: 2018,
    broadcast: {
      day: "Mondays",
      time: "01:35",
      timezone: "Asia/Tokyo",
      string: "Mondays at 01:35 (JST)",
    },
    producers: [[Object], [Object], [Object], [Object]],
    licensors: [],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object], [Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["family"],
  },
  {
    mal_id: 32281,
    url: "https://myanimelist.net/anime/32281/Kimi_no_Na_wa",
    images: { jpg: [Object], webp: [Object] },
    trailer: {
      youtube_id: "3KR8_igDs1Y",
      url: "https://www.youtube.com/watch?v=3KR8_igDs1Y",
      embed_url:
        "https://www.youtube.com/embed/3KR8_igDs1Y?enablejsapi=1&wmode=opaque&autoplay=1",
      images: [Object],
    },
    approved: true,
    titles: [[Object], [Object], [Object], [Object], [Object], [Object]],
    title: "Kimi no Na wa.",
    title_english: "Your Name.",
    title_japanese: "君の名は。",
    title_synonyms: [],
    type: "Movie",
    source: "Original",
    episodes: 1,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2016-08-26T00:00:00+00:00",
      to: null,
      prop: [Object],
      string: "Aug 26, 2016",
    },
    duration: "1 hr 46 min",
    rating: "PG-13 - Teens 13 or older",
    score: 8.86,
    scored_by: 1718518,
    rank: 24,
    popularity: 11,
    members: 2455219,
    favorites: 84064,
    synopsis:
      "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another. Kimi no Na wa. revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance. [Written by MAL Rewrite]",
    background:
      "Kimi no Na wa. won the LAFCA Animation Award in 2016 and the Best Animated Film in 2017 by Mainichi Film Awards. It also won the Grand Prize Award on the",
    season: null,
    year: null,
    broadcast: { day: null, time: null, timezone: null, string: null },
    producers: [[Object], [Object], [Object], [Object], [Object], [Object]],
    licensors: [[Object], [Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object]],
    demographics: [],
    stringGenres: ["action"],
  },
  {
    mal_id: 19,
    url: "https://myanimelist.net/anime/19/Monster",
    images: { jpg: [Object], webp: [Object] },
    trailer: { youtube_id: null, url: null, embed_url: null, images: [Object] },
    approved: true,
    titles: [[Object], [Object], [Object]],
    title: "Monster",
    title_english: "Monster",
    title_japanese: "モンスター",
    title_synonyms: [],
    type: "TV",
    source: "Manga",
    episodes: 74,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2004-04-07T00:00:00+00:00",
      to: "2005-09-28T00:00:00+00:00",
      prop: [Object],
      string: "Apr 7, 2004 to Sep 28, 2005",
    },
    duration: "24 min per ep",
    rating: "R+ - Mild Nudity",
    score: 8.85,
    scored_by: 327135,
    rank: 25,
    popularity: 150,
    members: 911028,
    favorites: 41911,
    synopsis:
      "Dr. Kenzou Tenma, an elite neurosurgeon recently engaged to his hospital director's daughter, is well on his way to ascending the hospital hierarchy. That is until one night, a seemingly small event changes Dr. Tenma's life forever. While preparing to perform surgery on someone, he gets a call from the hospital director telling him to switch patients and instead perform life-saving brain surgery on a famous performer. His fellow doctors, fiancée, and the hospital director applaud his accomplishment; but because of the switch, a poor immigrant worker is dead, causing Dr. Tenma to have a crisis of conscience. So when a similar situation arises, Dr. Tenma stands his ground and chooses to perform surgery on the young boy Johan Liebert instead of the town's mayor. Unfortunately, this choice leads to serious ramifications for Dr. Tenma—losing his social standing being one of them. However, with the mysterious death of the director and two other doctors, Dr. Tenma's position is restored. With no evidence to convict him, he is released and goes on to attain the position of hospital director. Nine years later when Dr. Tenma saves the life of a criminal, his past comes back to haunt him—once again, he comes face to face with the monster he operated on. He must now embark on a quest of pursuit to make amends for the havoc spread by the one he saved. [Written by MAL Rewrite]",
    background: null,
    season: "spring",
    year: 2004,
    broadcast: {
      day: "Wednesdays",
      time: "00:40",
      timezone: "Asia/Tokyo",
      string: "Wednesdays at 00:40 (JST)",
    },
    producers: [[Object], [Object], [Object]],
    licensors: [[Object]],
    studios: [[Object]],
    genres: [[Object], [Object], [Object]],
    explicit_genres: [],
    themes: [[Object], [Object]],
    demographics: [[Object]],
    stringGenres: ["action"],
  },
];
// 1)While chaining array methods, print the name of each movie that has a score above 8.0

// 2) While chaining array methods, print the name of each anime that "includes" the genre action
